[package]
name = "voip-client"
version = "1.0.1"
edition = "2021"

[[bin]]
name = "voip-client"
path = "src/main.rs"

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
byteorder = "1.4"
cpal = "0.15"
mdns-sd = "0.11"
sha2 = "0.10"
sentry = "0.34"
tauri-plugin-updater = "2"
tauri-plugin-single-instance = "2"
is_elevated = "0.1.2"
if-addrs = "0.13"

[build-dependencies]
tauri-build = { version = "2", features = [] }
